### PR TITLE
Fix missing import

### PR DESCRIPTION
**Pull request by nickvergessen**
```
Exception: Class 'OCA\SuspiciousLogin\Notifications\IAction' not found in file '/var/www/html/apps/suspicious_login/lib/Notifications/Notifier.php' line 93
```

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]
Someone did not test their code :rocket:

**Comment by nickvergessen** [comment]
> Error: Array to string conversion at /var/www/html/apps/suspicious_login/lib/Notifications/Notifier.php#90

Error line:
https://github.com/nextcloud/suspicious_login/blob/8eb3183720d6db8ff787c43be2f538d7f9624b9d/lib/Notifications/Notifier.php#L90

Variable comes from subject parameters which is an array:
https://github.com/nextcloud/suspicious_login/blob/8eb3183720d6db8ff787c43be2f538d7f9624b9d/lib/Notifications/Notifier.php#L76

`ip` seems to be the correct key, but please confirm
https://github.com/nextcloud/suspicious_login/blob/8eb3183720d6db8ff787c43be2f538d7f9624b9d/lib/Listener/LoginNotificationListener.php#L65

**Review by PVince81 — APPROVED** [review]
:+1:

**Pull request merged**
