### PR TITLE
Make training jobs time insensitive

### PR DESCRIPTION
**Pull request by PVince81**
Fixes https://github.com/nextcloud/suspicious_login/issues/608

### CODE REVIEW

**Review by ChristophWurst — CHANGES_REQUESTED** [review]
Needs checks because the main branch doesn't only target server master

**Comment by PVince81** [comment]
what kind of checks ? method existence ?

or set min-version to 23 ?

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/mail/blob/a30b96ec17f9103e7544100a5a5e5c7bcf51a112/lib/BackgroundJob/CleanupJob.php#L45-L50

**Comment by PVince81** [comment]
> https://github.com/nextcloud/mail/blob/a30b96ec17f9103e7544100a5a5e5c7bcf51a112/lib/BackgroundJob/CleanupJob.php#L45-L50

thanks a lot. I've adjusted the two jobs, please re-review

**Review by ChristophWurst — APPROVED** [review]

**Pull request merged**
