### PR TITLE
feat(workflows): add block-merge-freeze.yml

### PR DESCRIPTION
**Pull request by skjnldsv**

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]
:smiling_face_with_tear:

**Review by st3iny — APPROVED** [review]

**Comment by st3iny** [comment]
Now that everything is merged, the required checks have to adjusted to include the merge freeze action.

I can't do that due to insufficient permissions.

**Comment by ChristophWurst** [comment]
Done

**Pull request merged**
