### PR TITLE
Update master php testing versions

### PR DESCRIPTION
**Pull request by nickvergessen**
Signed-off-by: Joas Schilling <coding@schilljs.com>

### CODE REVIEW

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by PVince81** [comment]
seems we should remove php 7.3 ?

**Comment by nickvergessen** [comment]
> seems we should remove php 7.3 ?

No, still required: https://github.com/nextcloud/suspicious_login/blob/master/appinfo/info.xml#L29

**Comment by nickvergessen** [comment]
But yeah, should be moved to the matrix include

**Pull request merged**
