### PR TITLE
README.md: Fixed git clone command

### PR DESCRIPTION
**Pull request by Zocker1999NET**
The address of the `git clone`-command in the README file referred to another project, this pull request changes this address to this repository.

### CODE REVIEW

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/suspicious_login/pull/156/checks?check_run_id=223160510

**Comment by Zocker1999NET** [comment]
> https://github.com/nextcloud/suspicious_login/pull/156/checks?check_run_id=223160510

I already signed off the only commit correctly with my own GPG key (GitHub shows that the commit is verified), the same check failed before on 3bc7a7e which was signed off with the GitHub key because I commited on the website.

**Comment by ChristophWurst** [comment]
*sign off* and *sign* are two different things ;)

**Comment by Zocker1999NET** [comment]
Sorry, I misunderstood the term :man_facepalming:, thanks for your patience

**Comment by ChristophWurst** [comment]
No worries. Thanks for the fix :)

**Pull request merged**
